name: Trigger auto deployment for aicall-frontend-test

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/aicall-frontend-test-AutoDeployTrigger-b136c6d7-ad1c-4041-8977-cbd93c5f43f6.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write # This is required for requesting the OIDC JWT Token
      contents: read # Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AICALLFRONTENDTEST_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AICALLFRONTENDTEST_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AICALLFRONTENDTEST_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          dockerfilePath: ./Dockerfile  # Specify the correct Dockerfile path
          registryUrl: aicalltest.azurecr.io # Updated with the correct ACR name
          registryUsername: ${{ secrets.AICALLFRONTENDTEST_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.AICALLFRONTENDTEST_REGISTRY_PASSWORD }}
          containerAppName: aicall-frontend-test
          resourceGroup: DefaultResourceGroup-CID # Updated with the correct resource group name
          imageToBuild: aicalltest.azurecr.io/aicall-frontend-test:${{ github.sha }}
